USE REST_WITH_ASP_NET;

CREATE TABLE `persons` (
	`Id` INT(10) UNSIGNED NULL DEFAULT NULL,
	`FistName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
	`Address` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=InnoDB
;